# app/config/config.yml

liip_imagine:
    resolvers:
        default:
            web_path: ~
    filter_sets:
        news:
            quality: 75
            filters:
                thumbnail: { size: [360, 270], mode: outbound }
