---
version: '2'

services:
  web:
    image: $WEB_IMAGE
    labels:
      io.rancher.container.pull_image: always
      traefik.docker.network: proxy
      traefik.enable: true
      traefik.frontend.passHostHeader: true
      traefik.frontend.rule: 'Host:$HTTP_URL'
      traefik.frontend.entryPoints: http,https
      traefik.port: 80
      traefik.frontend.headers.SSLRedirect: true
    restart: always
