---
version: '3.6'

services:
  web:
    build:
      context: .
      target: dev
    restart: always
    env_file:
      - .env
    ports:
      - ${WEB_PORT}:80/tcp
    volumes:
      - './assets:/var/www/html/assets'
      - './bin:/var/www/html/bin'
      - './config:/var/www/html/config'
      - './Existenzgruendung-Developer-Startup.jpg:/var/www/html/Existenzgruendung-Developer-Startup.jpg'
      - './gv.php:/var/www/html/gv.php'
      - './package.json:/var/www/html/package.json'
      - './phpcs.xml:/var/www/html/phpcs.xml'
      - './public:/var/www/html/public'
      - './src:/var/www/html/src'
      - './templates:/var/www/html/templates'
      - './tests:/var/www/html/tests'
      - './translations:/var/www/html/translations'
      - './webpack.config.js:/var/www/html/webpack.config.js'
      - './Never-Code-Alone-Page-b3030ac27acc.json:/var/www/html/Never-Code-Alone-Page-b3030ac27acc.json'
      - '/etc/passwd:/etc/passwd'
      - '/etc/group:/etc/group'
